spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/semogong
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
        format_sql : true


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace # p6spy로 대체
