spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/semogong #  jdbc:mysql://${DB_URL}:3306/semogong
    username: park  # ${DB_NAME}
    password:  # ${DB_PASSWORD}
    driver-class-name: org.h2.Driver # com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto : create # update
    properties:
      hibernate:
        format_sql : true

  servlet:
    multipart:
      location: C:\Users\bob8d\OneDrive\Desktop\Semgong\semogong\src\main\resources\static\images
      maxFileSize: 10MB
      maxRequestSize: 20MB


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace # p6spy로 대체
